### ISSUE TITLE
Not enough information to paginate

### ISSUE THREAD

**Issue by haz00** [DrewCarlson/CoinGecko-Kotlin#16]
CoinGecko API responds with HTTP-header `rel="next"  per-page: 100  total: 159 ` or `rel="last", <https://api.coingecko.com/api/v3/coins/tether/tickers?exchange_ids=binance&page=2>` 
for some requests e.g `https://api.coingecko.com/api/v3/coins/tether/tickers?exchange_ids=binance` 

I have not found any information on how the library works with these headers, but they are really needed for correct pagination.

**Comment by DrewCarlson** [comment]
Thanks for the report.  Response headers are not accessible as this library only returns response bodies.  Since pagination information is only available in headers I'm thinking it will be required to copy the relevant information into the response model.

Since that endpoint pages every 100 items, you could attempt to load the next page anytime `tickers` contains that many items.  If it contains less than 100 items there are no additional pages to load, loading the next page if there are no more items simply results in an empty `tickers` list.

**Comment by DrewCarlson** [comment]
In `0.1.7` paged responses, including `CoinTickerById`, implement `Page`:
```kotlin
interface Page {
    val total: Int
    val perPage: Int
    val nextPage: Int?
    val previousPage: Int?
}
```
